from rdkit import Chem
from torch_geometric.data import (Data, InMemoryDataset,Dataset ,download_url,
                                  extract_gz)
import pickle
import torch
import os
import argparse
import numpy as np

x_map = {
    'atomic_num':
        list(range(0, 119)),
    'chirality': [
        'CHI_UNSPECIFIED',
        'CHI_TETRAHEDRAL_CW',
        'CHI_TETRAHEDRAL_CCW',
        'CHI_OTHER',
    ],
    'degree':
        list(range(0, 11)),
    'formal_charge':
        list(range(-5, 7)),
    'num_hs':
        list(range(0, 9)),
    'num_radical_electrons':
        list(range(0, 5)),
    'hybridization': [
        'UNSPECIFIED',
        'S',
        'SP',
        'SP2',
        'SP3',
        'SP3D',
        'SP3D2',
        'OTHER',
    ],
    'is_aromatic': [False, True],
    'is_in_ring': [False, True],
}

e_map = {
    'bond_type': [
        'misc',
        'SINGLE',
        'DOUBLE',
        'TRIPLE',
        'AROMATIC',
    ],
    'stereo': [
        'STEREONONE',
        'STEREOZ',
        'STEREOE',
        'STEREOCIS',
        'STEREOTRANS',
        'STEREOANY',
    ],
    'is_conjugated': [False, True],
}

class MyOwnDataset(InMemoryDataset):
    def __init__(self, root, dataset_name, csv_suffix=".csv", pkl_suffix="_3d_branch_conformer_data.pkl",
                 transform=None, pre_transform=None, pre_filter=None):
        self.dataset_name = dataset_name.lower()
        self.csv_suffix = csv_suffix
        self.pkl_suffix = pkl_suffix
        super().__init__(root, transform, pre_transform, pre_filter)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def processed_file_names(self):
        # PyG will create processed/data.pt
        return 'data.pt'

    @property
    def raw_file_names(self):
        # PyG checks these files must exist in raw/ pkl file generated by 3d unimol directory
        return [
            f"{self.dataset_name}{self.pkl_suffix}",
        ]
        # return [ "BBBP_3d_branch_conformer_data.pkl"]

    def download(self):
        pass

    def process(self):
        # load data
        print("load_data")
        path_dataset_pkl = self.raw_paths[0]
        print(path_dataset_pkl)
        with open(path_dataset_pkl, 'rb') as file:
           data_dict = pickle.load(file)
        #dict_keys(
        #    ['raw_data', 'raw_target', 'num_classes', 'target_cols', 'multiclass_cnt', 'smiles', 'scaffolds', 'group',
        #     'target_scaler', 'target', 'unimol_input'])
        length = len(data_dict['smiles'])
        # test
        print(length)
        print("----------")
        '''
        smiles:
        target:
        unimol_input:
             src_tokens:
             src_distance:
             src_coord:
             src_edge_type:
        '''

        datalist = []
        for i in range(len(data_dict['smiles'])):
            smiles = data_dict['smiles'][i]
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                continue
            nodes_feature=[]
            for atom in mol.GetAtoms():
                node_feature = []
                node_feature.append(x_map['atomic_num'].index(atom.GetAtomicNum()))
                node_feature.append(x_map['chirality'].index(str(atom.GetChiralTag())))
                node_feature.append(x_map['degree'].index(atom.GetTotalDegree()))
                node_feature.append(x_map['formal_charge'].index(atom.GetFormalCharge()))
                node_feature.append(x_map['num_hs'].index(atom.GetTotalNumHs()))
                node_feature.append(x_map['num_radical_electrons'].index(
                    atom.GetNumRadicalElectrons()))
                node_feature.append(x_map['hybridization'].index(
                    str(atom.GetHybridization())))
                node_feature.append(x_map['is_aromatic'].index(atom.GetIsAromatic()))
                node_feature.append(x_map['is_in_ring'].index(atom.IsInRing()))
                nodes_feature.append(node_feature)
            x = torch.tensor(nodes_feature, dtype=torch.float).view(-1, 9)

            edge_indices, edge_attrs = [], []
            for bond in mol.GetBonds():
                k = bond.GetBeginAtomIdx()
                j = bond.GetEndAtomIdx()

                # e = []
                # e.append(e_map['bond_type'].index(str(bond.GetBondType())))
                # e.append(e_map['stereo'].index(str(bond.GetStereo())))
                # e.append(e_map['is_conjugated'].index(bond.GetIsConjugated()))

                edge_indices += [[k, j], [j, k]]
                # edge_attrs += [e, e]

            edge_index = torch.tensor(edge_indices)
            edge_index = edge_index.t().to(torch.long).view(2, -1)

            t = np.asarray(data_dict['target'][i], dtype=np.float32)
            t = np.where(t == np.iinfo(np.int32).min, np.nan, t).astype(np.float32)

            y = torch.from_numpy(t)  # 允许 NaN
            y_mask = torch.from_numpy(~np.isnan(t))  # bool

            # y = torch.from_numpy(t).view(1, -1)  # [1, 27]
            # y_mask = torch.from_numpy(~np.isnan(t)).view(1, -1)  # [1, 27]

            unimol_input = data_dict['unimol_input'][i]

            data = Data(
                x=x,
                edge_index=edge_index,
                y=y,  # [T]
                y_mask=y_mask,  # [T] bool
                smiles=smiles,
                unimol_input=unimol_input
            )
            datalist.append(data)
        data, slices = self.collate(datalist)
        torch.save((data, slices), self.processed_paths[0])



import sys
sys.path.append(r"E:/PycharmProjects/3Dmodality/src/branch_3D")
import src.branch_3D.uni_tool
from src.branch_3D.util import DATASET_DIR

from collections import Counter


import util as sd
from src.branch_3D import UniMolModel

if __name__ == '__main__':
    datasets   = ["clintox_CT_TOX", "clintox_FDA_APPROVED"]
    seeds      = [0, 1, 2]

    for dataset in datasets:
        for random_seed in seeds:
            print(f"\n{'='*50}")
            print(f"Processing dataset={dataset} | seed={random_seed}")
            print(f"{'='*50}")

            # ── Load dataset ──────────────────────────────────────
            molecular_dataset = MyOwnDataset(
                root=str(DATASET_DIR / dataset),
                dataset_name=dataset
            )

            # ── Load model (only needed for collate_fn) ───────────
            model_batch = UniMolModel(
                output_dim=767,
                data_type="molecule",
                remove_hs=False
            )

            # ── Generate & save anchor split ──────────────────────
            train_loader, valid_loader, test_loader, \
            train_size, valid_size, test_size = \
                sd.random_scaffold_split_generate_anchor(
                    dataset=molecular_dataset,
                    null_value=0,
                    smiles_list=[],
                    frac_train=0.8,
                    frac_valid=0.1,
                    frac_test=0.1,
                    seed=random_seed,
                    batch_size=16,
                    collate_fn=model_batch.batch_collate_fn_2,
                    save_split=True,
                    split_name=f"{dataset}_seed{random_seed}"
                )

            print(f"[Done] {dataset} seed={random_seed} → "
                  f"train={train_size} | valid={valid_size} | test={test_size}")